[package]
name = "app-state"
version = "0.1.0"
edition = "2024"

[dependencies]
gaggle-core = { path = "../core" }
net = { path = "../net" }
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
base64 = "0.22"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
tempfile = "3"
