//! Per-share signing identity.
//!
//! Every private share has its own Ed25519 keypair, generated by the origin.
//! The secret half never leaves the origin; the public half is the share's
//! *authority* — distinct from [`Manifest::id`](crate::Manifest::id), which is a
//! content address. An [`Invite`](crate::invite::Invite) carries the public key
//! plus a [`SignedCapability`](crate::invite::SignedCapability) the origin signed
//! with the secret half, so a subscriber can prove to swarm peers that it was
//! let in — without any of them holding the secret.

use std::fmt;

use ed25519_dalek::{Signer, SigningKey, VerifyingKey};
use serde::{Deserialize, Deserializer, Serialize, Serializer};

use crate::error::{Error, Result};
use crate::hash::Hash;

/// A share's full signing keypair. Hold this only on the origin.
pub struct ShareKeypair(SigningKey);

impl ShareKeypair {
    /// Generate a fresh random keypair.
    pub fn generate() -> Self {
        let mut seed = [0u8; 32];
        getrandom::getrandom(&mut seed).expect("system RNG unavailable");
        Self(SigningKey::from_bytes(&seed))
    }

    /// Deterministic keypair from a 32-byte seed (tests, key derivation).
    pub fn from_seed(seed: [u8; 32]) -> Self {
        Self(SigningKey::from_bytes(&seed))
    }

    /// The 32-byte secret seed — persist this to keep issuing invites later.
    pub fn to_seed(&self) -> [u8; 32] {
        self.0.to_bytes()
    }

    /// The public half to put in invites and hand to swarm peers.
    pub fn public(&self) -> SharePublicKey {
        SharePublicKey(self.0.verifying_key().to_bytes())
    }

    /// Sign `msg` (already domain-separated by the caller).
    pub(crate) fn sign(&self, msg: &[u8]) -> Signature {
        Signature(self.0.sign(msg).to_bytes())
    }
}

impl fmt::Debug for ShareKeypair {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // Never print secret material.
        write!(f, "ShareKeypair({})", self.public())
    }
}

/// The public identity of a share. Cheap to copy, safe to publish.
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub struct SharePublicKey([u8; 32]);

impl SharePublicKey {
    pub const LEN: usize = 32;

    pub const fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }

    pub const fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }

    /// A short stable handle for this key: `blake3(pubkey)`. Handy as a map key
    /// or log tag.
    pub fn id(&self) -> Hash {
        Hash::of(&self.0)
    }

    pub fn to_hex(self) -> String {
        let mut s = String::with_capacity(64);
        for b in self.0 {
            s.push_str(&format!("{b:02x}"));
        }
        s
    }

    pub fn from_hex(s: &str) -> Result<Self> {
        if s.len() != 64 {
            return Err(Error::Invite(format!("share key hex must be 64 chars, got {}", s.len())));
        }
        let mut out = [0u8; 32];
        for (i, byte) in out.iter_mut().enumerate() {
            *byte = u8::from_str_radix(&s[i * 2..i * 2 + 2], 16)
                .map_err(|e| Error::Invite(format!("bad share key hex: {e}")))?;
        }
        Ok(Self(out))
    }

    /// Verify `sig` over `msg` against this key. Uses `verify_strict` — a
    /// malleable or non-canonical signature (non-canonical `S`, small-order `A`)
    /// is rejected, so a capability token has exactly one valid encoding.
    pub(crate) fn verify(&self, msg: &[u8], sig: &Signature) -> Result<()> {
        let vk = VerifyingKey::from_bytes(&self.0)
            .map_err(|e| Error::Invite(format!("not a valid Ed25519 public key: {e}")))?;
        let sig = ed25519_dalek::Signature::from_bytes(&sig.0);
        vk.verify_strict(msg, &sig)
            .map_err(|_| Error::Invite("signature does not verify".into()))
    }
}

impl fmt::Debug for SharePublicKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "SharePublicKey({}…)", &self.to_hex()[..10])
    }
}

impl fmt::Display for SharePublicKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.to_hex())
    }
}

impl Serialize for SharePublicKey {
    fn serialize<S: Serializer>(&self, s: S) -> std::result::Result<S::Ok, S::Error> {
        if s.is_human_readable() {
            s.serialize_str(&self.to_hex())
        } else {
            s.serialize_bytes(&self.0)
        }
    }
}

impl<'de> Deserialize<'de> for SharePublicKey {
    fn deserialize<D: Deserializer<'de>>(d: D) -> std::result::Result<Self, D::Error> {
        use serde::de::Error as _;
        if d.is_human_readable() {
            let s = String::deserialize(d)?;
            Self::from_hex(&s).map_err(D::Error::custom)
        } else {
            let bytes = <Vec<u8>>::deserialize(d)?;
            let arr: [u8; 32] =
                bytes.try_into().map_err(|_| D::Error::custom("share key must be 32 bytes"))?;
            Ok(Self(arr))
        }
    }
}

/// A detached Ed25519 signature.
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct Signature([u8; 64]);

impl Signature {
    pub const LEN: usize = 64;

    pub const fn from_bytes(bytes: [u8; 64]) -> Self {
        Self(bytes)
    }

    pub const fn to_bytes(self) -> [u8; 64] {
        self.0
    }
}

impl fmt::Debug for Signature {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Signature({:02x}{:02x}…)", self.0[0], self.0[1])
    }
}

impl Serialize for Signature {
    fn serialize<S: Serializer>(&self, s: S) -> std::result::Result<S::Ok, S::Error> {
        use base64::Engine;
        if s.is_human_readable() {
            s.serialize_str(&base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(self.0))
        } else {
            s.serialize_bytes(&self.0)
        }
    }
}

impl<'de> Deserialize<'de> for Signature {
    fn deserialize<D: Deserializer<'de>>(d: D) -> std::result::Result<Self, D::Error> {
        use base64::Engine;
        use serde::de::Error as _;
        let bytes = if d.is_human_readable() {
            let s = String::deserialize(d)?;
            base64::engine::general_purpose::URL_SAFE_NO_PAD
                .decode(s.as_bytes())
                .map_err(D::Error::custom)?
        } else {
            <Vec<u8>>::deserialize(d)?
        };
        let arr: [u8; 64] =
            bytes.try_into().map_err(|_| D::Error::custom("signature must be 64 bytes"))?;
        Ok(Self(arr))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sign_and_verify_round_trip() {
        let kp = ShareKeypair::from_seed([7u8; 32]);
        let pk = kp.public();
        let sig = kp.sign(b"hello");
        assert!(pk.verify(b"hello", &sig).is_ok());
        assert!(pk.verify(b"hell0", &sig).is_err());

        let other = ShareKeypair::generate().public();
        assert!(other.verify(b"hello", &sig).is_err());
    }

    #[test]
    fn from_seed_is_deterministic() {
        let a = ShareKeypair::from_seed([1u8; 32]).public();
        let b = ShareKeypair::from_seed([1u8; 32]).public();
        assert_eq!(a, b);
        assert_ne!(a, ShareKeypair::from_seed([2u8; 32]).public());
    }

    #[test]
    fn public_key_hex_round_trips() {
        let pk = ShareKeypair::from_seed([9u8; 32]).public();
        assert_eq!(SharePublicKey::from_hex(&pk.to_hex()).unwrap(), pk);
        assert!(SharePublicKey::from_hex("zz").is_err());
    }

    #[test]
    fn seed_round_trips() {
        let kp = ShareKeypair::generate();
        let restored = ShareKeypair::from_seed(kp.to_seed());
        assert_eq!(kp.public(), restored.public());
    }

    #[test]
    fn signature_json_round_trips() {
        let sig = ShareKeypair::from_seed([3u8; 32]).sign(b"x");
        let json = serde_json::to_string(&sig).unwrap();
        assert_eq!(serde_json::from_str::<Signature>(&json).unwrap(), sig);
    }
}
